<script setup>
import { ref, computed, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import { useAlert } from 'dashboard/composables';
import { useSidebarLayout } from 'dashboard/composables/useSidebarLayout';
import { applyLayout } from 'dashboard/components-next/sidebar/helper/applyLayout';
import SidebarLayoutAPI from 'dashboard/api/sidebarLayout';
import Button from 'dashboard/components-next/button/Button.vue';
import Icon from 'dashboard/components-next/icon/Icon.vue';

const { t } = useI18n();
// The menu comes from the sidebar itself, so the preview runs on exactly what
// the real sidebar renders instead of a rebuilt guess.
const { layout: savedLayout, setLayout, menu } = useSidebarLayout();

const groups = ref([]);
const items = ref({});
const isSaving = ref(false);

// A group id is generated by us and never reuses a menu item's `name`, so that
// deleting a group can never take an item down with it.
const newGroupId = () => `g_${Date.now()}_${Math.floor(Math.random() * 1e4)}`;

onMounted(() => {
  const saved = savedLayout.value || {};
  groups.value = Array.isArray(saved.groups)
    ? structuredClone(saved.groups)
    : [];
  items.value = saved.items ? structuredClone(saved.items) : {};
});

const draft = computed(() => ({
  version: 1,
  groups: groups.value,
  items: items.value,
}));

// The same function the sidebar runs. Anything else would be a preview of a
// menu nobody will ever see.
const preview = computed(() => applyLayout(menu.value, draft.value));

const ruleFor = name => {
  if (!items.value[name]) items.value[name] = {};
  return items.value[name];
};

// Only leaves can be adopted: a native group inside a custom one would be a
// third level, which the sidebar does not render.
const adoptable = computed(() =>
  menu.value.filter(
    entry => !(Array.isArray(entry.children) && entry.children.length)
  )
);

const looseItems = computed(() =>
  adoptable.value.filter(entry => !items.value[entry.name]?.group)
);

const itemsIn = groupId =>
  adoptable.value.filter(entry => items.value[entry.name]?.group === groupId);

const addGroup = () => {
  groups.value.push({
    id: newGroupId(),
    label: t('SIDEBAR_ORGANISER.NEW_GROUP'),
    order: groups.value.length,
  });
};

const removeGroup = id => {
  groups.value = groups.value.filter(group => group.id !== id);
  // The items go home rather than down with the group.
  Object.values(items.value).forEach(rule => {
    if (rule.group === id) delete rule.group;
  });
};

const moveTo = (name, groupId) => {
  const rule = ruleFor(name);
  if (groupId) rule.group = groupId;
  else delete rule.group;
};

const toggleHidden = name => {
  const rule = ruleFor(name);
  rule.hidden = !rule.hidden;
};

const rename = (name, label) => {
  const rule = ruleFor(name);
  const trimmed = (label || '').trim();
  if (trimmed) rule.label = trimmed;
  else delete rule.label;
};

const save = async () => {
  isSaving.value = true;
  try {
    const { data } = await SidebarLayoutAPI.update(draft.value);
    // Updates the live sidebar without a reload.
    setLayout(data.layout);
    useAlert(t('SIDEBAR_ORGANISER.SAVED'));
  } catch (error) {
    useAlert(t('SIDEBAR_ORGANISER.SAVE_FAILED'));
  } finally {
    isSaving.value = false;
  }
};

const resetAll = () => {
  groups.value = [];
  items.value = {};
};
</script>

<template>
  <div class="flex flex-col gap-6 p-6">
    <header class="flex items-start justify-between gap-4">
      <div class="flex flex-col gap-1">
        <h1 class="text-xl font-medium text-n-slate-12">
          {{ t('SIDEBAR_ORGANISER.TITLE') }}
        </h1>
        <p class="m-0 text-sm text-n-slate-11 max-w-2xl">
          {{ t('SIDEBAR_ORGANISER.SUBTITLE') }}
        </p>
      </div>
      <div class="flex items-center gap-2 flex-shrink-0">
        <Button
          variant="ghost"
          :label="t('SIDEBAR_ORGANISER.RESET')"
          @click="resetAll"
        />
        <Button
          :label="t('SIDEBAR_ORGANISER.SAVE')"
          :is-loading="isSaving"
          @click="save"
        />
      </div>
    </header>

    <div class="grid grid-cols-1 lg:grid-cols-[1fr_20rem] gap-6 items-start">
      <div class="flex flex-col gap-4">
        <section class="flex flex-col gap-2">
          <div class="flex items-center justify-between">
            <h2 class="text-sm font-medium text-n-slate-12">
              {{ t('SIDEBAR_ORGANISER.GROUPS') }}
            </h2>
            <Button
              size="sm"
              variant="ghost"
              icon="i-lucide-plus"
              :label="t('SIDEBAR_ORGANISER.ADD_GROUP')"
              @click="addGroup"
            />
          </div>

          <p v-if="!groups.length" class="m-0 text-[13px] text-n-slate-11">
            {{ t('SIDEBAR_ORGANISER.NO_GROUPS') }}
          </p>

          <div
            v-for="group in groups"
            :key="group.id"
            class="flex flex-col gap-2 p-3 rounded-lg border border-n-weak bg-n-solid-1"
          >
            <div class="flex items-center gap-2">
              <Icon icon="i-lucide-folder" class="size-4 text-n-slate-11" />
              <input
                v-model="group.label"
                class="flex-1 bg-transparent text-sm font-medium text-n-slate-12 outline-none"
                :aria-label="t('SIDEBAR_ORGANISER.GROUP_NAME')"
              />
              <Button
                size="sm"
                variant="ghost"
                color="ruby"
                icon="i-lucide-trash-2"
                @click="removeGroup(group.id)"
              />
            </div>

            <div
              v-for="entry in itemsIn(group.id)"
              :key="entry.name"
              class="flex items-center gap-2 pl-6"
            >
              <span class="flex-1 text-[13px] text-n-slate-12 truncate">
                {{ items[entry.name]?.label || entry.label }}
              </span>
              <Button
                size="sm"
                variant="ghost"
                :icon="
                  items[entry.name]?.hidden
                    ? 'i-lucide-eye-off'
                    : 'i-lucide-eye'
                "
                @click="toggleHidden(entry.name)"
              />
              <Button
                size="sm"
                variant="ghost"
                icon="i-lucide-corner-up-left"
                @click="moveTo(entry.name, null)"
              />
            </div>
          </div>
        </section>

        <section class="flex flex-col gap-2">
          <h2 class="text-sm font-medium text-n-slate-12">
            {{ t('SIDEBAR_ORGANISER.LOOSE') }}
          </h2>
          <p class="m-0 text-[13px] text-n-slate-11">
            {{ t('SIDEBAR_ORGANISER.LOOSE_HINT') }}
          </p>
          <div
            v-for="entry in looseItems"
            :key="entry.name"
            class="flex items-center gap-2 p-2 rounded-lg border border-n-weak"
          >
            <span class="flex-1 text-[13px] text-n-slate-12 truncate">
              {{ items[entry.name]?.label || entry.label }}
            </span>
            <input
              :value="items[entry.name]?.label || ''"
              :placeholder="t('SIDEBAR_ORGANISER.RENAME')"
              class="w-32 px-2 py-1 text-[12px] rounded bg-n-alpha-1 outline-none text-n-slate-12"
              @change="rename(entry.name, $event.target.value)"
            />
            <Button
              size="sm"
              variant="ghost"
              :icon="
                items[entry.name]?.hidden ? 'i-lucide-eye-off' : 'i-lucide-eye'
              "
              @click="toggleHidden(entry.name)"
            />
            <select
              class="text-[12px] rounded bg-n-alpha-1 px-2 py-1 text-n-slate-12"
              :value="items[entry.name]?.group || ''"
              @change="moveTo(entry.name, $event.target.value || null)"
            >
              <option value="">{{ t('SIDEBAR_ORGANISER.TOP') }}</option>
              <option v-for="group in groups" :key="group.id" :value="group.id">
                {{ group.label }}
              </option>
            </select>
          </div>
        </section>
      </div>

      <aside
        class="flex flex-col gap-1 p-3 rounded-lg border border-n-weak bg-n-solid-1 sticky top-6"
      >
        <h2 class="text-sm font-medium text-n-slate-12 mb-1">
          {{ t('SIDEBAR_ORGANISER.PREVIEW') }}
        </h2>
        <div
          v-for="entry in preview"
          :key="entry.name"
          class="flex flex-col gap-1"
        >
          <span
            class="flex items-center gap-2 text-[13px] text-n-slate-12 px-2 py-1 rounded"
            :class="entry.children ? 'font-medium' : ''"
          >
            <Icon
              :icon="entry.icon || 'i-lucide-circle-small'"
              class="size-4 flex-shrink-0 text-n-slate-11"
            />
            {{ entry.label }}
          </span>
          <span
            v-for="child in entry.children || []"
            :key="child.name"
            class="pl-8 text-[12px] text-n-slate-11 truncate"
          >
            {{ child.label }}
          </span>
        </div>
      </aside>
    </div>
  </div>
</template>
