# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'UniverZAP'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.svg'
- name: BRAND_URL
  value: 'https://univerzap.cloud'
- name: WIDGET_BRAND_URL
  value: 'https://univerzap.cloud'
- name: BRAND_NAME
  value: 'UniverZAP'
- name: TERMS_URL
  value: 'https://univerzap.cloud/terms'
- name: PRIVACY_URL
  value: 'https://univerzap.cloud/privacy'
- name: DISPLAY_MANIFEST
  value: false
# ------- End of Branding Related Config ------- #
