// Stable fixtures that mirror the `Task#push_event_data` payload shape so
// store specs don't drift from the real backend response.

export const tasksList = [
  {
    id: 1,
    display_id: 1,
    account_id: 1,
    created_by_user_id: 7,
    title: 'Send the proposal',
    description: { type: 'doc', text: 'Send it to the lead.' },
    status: 'open',
    urgency: 'urgent',
    due_date: 1735689600,
    completed_at: null,
    notify_assignees: true,
    custom_attributes: {},
    position: 0,
    assignees: [
      { id: 7, name: 'Alex', avatar_url: '' },
      { id: 8, name: 'Maria', avatar_url: '' },
    ],
    comments_count: 1,
    activities_count: 1,
    created_at: 1735603200,
    updated_at: 1735603200,
  },
  {
    id: 2,
    display_id: 2,
    account_id: 1,
    created_by_user_id: 7,
    title: 'Follow up call',
    description: {},
    status: 'open',
    urgency: 'high',
    due_date: null,
    completed_at: null,
    notify_assignees: true,
    custom_attributes: {},
    position: 1,
    assignees: [{ id: 7, name: 'Alex', avatar_url: '' }],
    comments_count: 0,
    activities_count: 1,
    created_at: 1735603300,
    updated_at: 1735603300,
  },
  {
    id: 3,
    display_id: 3,
    account_id: 1,
    created_by_user_id: 9,
    title: 'Internal review',
    description: {},
    status: 'in_progress',
    urgency: 'low',
    due_date: null,
    completed_at: null,
    notify_assignees: true,
    custom_attributes: {},
    position: 2,
    assignees: [],
    comments_count: 0,
    activities_count: 0,
    created_at: 1735603400,
    updated_at: 1735603400,
  },
];

export default tasksList;
